; Dart tags.scm — verified against actual AST

; functions
(function_signature
  name: (identifier) @name) @definition.function

; classes
(class_definition
  name: (identifier) @name) @definition.class

; enum
(enum_declaration
  name: (identifier) @name) @definition.class

; mixin
(mixin_declaration
  name: (identifier) @name) @definition.class

; imports (library_import may not be generated by all dart grammar versions)
(library_import) @import
(library_export) @import
(import_or_export) @import
